### ISSUE TITLE
Session id not working 

### ISSUE THREAD

**Issue by Wallyjaytechy** [AbhishekSuresh2/Phoenix-MD#162]
Please try
And check out to solve the sess
session if generating problem

**Comment by Comradeventure1** [comment]
Alright

**Comment by Wallyjaytechy** [comment]
Please sir solve the issue for us as soon as possible i have many friends
that want to install it but it's failing because of the session id heroku
not working could you set up another easier way of getting session id than
using heroku

**Comment by AbhishekSuresh2** [comment]
Sorry guys i m stoped this project making new project soon
