### ISSUE TITLE
Session id malfunction 

### ISSUE THREAD

**Issue by Wallyjaytechy** [AbhishekSuresh2/Phoenix-MD#220]
The Phoenix md session id not working it says this 👇 
![Screenshot_20240715-104840](https://github.com/user-attachments/assets/5f365e24-979c-4698-8e8d-5e0f14e0685b)

**Comment by Marcosgithub338** [comment]
Same here. How do we solve this

**Comment by FahimCreatior** [comment]
Uodate it on left sync. Worked for me
